### ISSUE TITLE
Only the number of matches in the viewport are shown in the status bar

### ISSUE THREAD

**Issue by andrezgz** [Krusty84/obsidian-occura-plugin#1]
After clicking a word I was hoping to get the _total_ number of matches found within the whole document. But the status bar only shows the number of matches inside the viewport i.e. the part of the document that's visible.

If I scroll down or up the number updates based on how many matches are now displayed.

**Comment by andrezgz** [comment]
Found this recent change in Obsidian changelog that may be related to this https://docs.obsidian.md/Plugins/Guides/Understanding+deferred+views

**Comment by Krusty84** [comment]
I will check, thanks!

**Comment by Krusty84** [comment]
@andrezgz I have reproduced this behavior, thanks I will fix it.
