### ISSUE TITLE
Feature request: Preview mode support

### ISSUE THREAD

**Issue by matisync** [Krusty84/obsidian-occura-plugin#2]
Hi, is it possible that the plugin works also in preview mode?

**Comment by Krusty84** [comment]
Hello @matisync mmm, I have checked now, and highlighting works in Live Preview... (1.7.4, MacOS)

**Comment by matisync** [comment]
Hi @Krusty84!, to do a direct test I created a new vault, I didn't change the default theme and just installed the Occura plugin. But in live preview I can't get it to highlight the text. I'm using Linux Mint and Obsidian 1.7.4

![Occura Test](https://github.com/user-attachments/assets/0275ebaa-8808-4d32-a4a4-8723c260d0df)

**Comment by Krusty84** [comment]
Dear @matisync based on your picture, Obsidian has Reading mode, and In the Reading mode the plugin does not work. I will be looking for the way to solve it in future.

**Comment by matisync** [comment]
Thanks!
