### ISSUE TITLE
The plugin function is excellent thank Please add custom highlighted text

### ISSUE THREAD

**Issue by 0xChrisJL** [Krusty84/obsidian-occura-plugin#4]
The plugin function is excellent thank

Can suggest adding custom add a set of words or multiple sets of words to the plugin function, and highlight these words by default.

Inspiration source:An automatic highlighting plugin for Google Chrome browser    [auto-highlight]
https://chromewebstore.google.com/detail/auto-highlight/ndndibnggapaodjdfoeehgmmpppedgfb

**Comment by Krusty84** [comment]
Hello @0xChrisJL Thanks for the idea!

**Comment by Krusty84** [comment]
@0xChrisJL I have added it in 1.3.0 release
again, thanks for idea!

**Comment by 0xChrisJL** [comment]
thank you very much  ^_^
